### ISSUE TITLE
TODO checklist

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaCoreUtils#64]
Items as they come up:

-----
_TODO:_

- [ ] `setIfNull()` mishandles integer input:  `slice <- MazamaCoreUtils::setIfNull(slice, "max")` (05/04/26)
- [ ] add `timeStamp(style = "human")` to  produce "clock" style without the 'T' (10/12/24)

----

_Items finished by 2024-12-02_

- [x] `loadDataFile()` should allow for prioritization of either local or remote; improve documentation; add example

----

_Items finished by 2024-02-07_

- [x] `initializeLogging()` should create `WARN.log`.

----
_Items finished by 2023-11-13_

- [x] add `precision` argument to `creeateLocationID()`. (11/13)
- [x] CRAN tests failure. (11/13)

----
_Items finished by 2023-10-26_

- [x] `initializeLogging()` doesn't use `filePrefix` in the creation of new log file names. (9/16)
- [x] `timeStamp()` should have the first parameter should default to `lubridate::now(tzone = "UTC")` -- a super common use case. (10/26)
- [x] Need to import/export another function so we don't see this:
`WARN [2023-08-29 14:06:58] Oops: object 'flog.appender' not found` (8/29)
- [x] Need a `createLocationMask()` function. (10/26)
- [x] `createLocationID()` should return NA for invalid locations. (10/26)
